# fly.toml app configuration file generated for fly-io-nest-sample on 2024-08-19T21:45:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-io-nest-sample'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
